name: Compile LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile Document
        run: latexmk -pdfxe ctufit-thesis.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Thesis
          path: ctufit-thesis.pdf
