name: Compile LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile Document
        run: latexmk -pdfxe ctufit-thesis.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis-dobryjak
          path: out/ctufit-thesis.pdf
