name: Compile LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    container:
      image: texlive/texlive:latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile Document
        run: latexmk -pdfxe ctufit-thesis.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: thesis-dobryjak
          path: out/ctufit-thesis.pdf

      # Step to comment the link to the artifacts on PR
      - name: Comment PR with Artifact Link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const artifactUrl = `https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}`;
            const prComment = `The compiled PDF can be found here: [Download PDF](${artifactUrl})`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: prComment
            });